zookeeper:
  image: jplock/zookeeper:3.4.6
  ports:
    - "2181:2181"

postgres:
        #build: ./postgres
  image: twistdroach/postgres
  ports:
    - "5432:5432"

hadoop: #used for both HDFS deep storage and Hadoop batch indexing
  image: twistdroach/hadoop
  #build: ./hadoop #putting hostname into core-site.xml is fixed in later versions, but not 2.3.0
  volumes:
    - /Users:/Users
  hostname: hadoop
  ports:
    - "9000:9000" #hdfs name node client
    - "50070:50070" #hdfs name node web ui
    - "8088:8088" #yarn web ui
    - "8032:8032" #yarn resource manager client
    - "50075:50075"
    - "50020:50020"
    - "50090:50090"
    - "50010:50010"
    - "8030:8030"
    - "55071:55071"
    - "8031:8031"
    - "8033:8033"
    - "8040:8040"
    - "8042:8042"
    - "13562:13562"
    - "10020:10020" #job history
    - "19888:19888" #job history web ui

druidbroker1:
  image: banno/druid-broker:latest
  links:
    - zookeeper
  ports:
    - "8082:8082"
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M
    druid_host: druidbroker1
    druid_port: 8082
    druid_zk_service_host: zookeeper:2181
    druid_processing_buffer_sizeBytes: 52428800 #50 * 1024 * 1024

druidbroker2:
  image: banno/druid-broker:latest
  links:
    - zookeeper
  ports:
    - "8182:8182"
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M
    druid_host: druidbroker2
    druid_port: 8182
    druid_zk_service_host: zookeeper:2181
    druid_processing_buffer_sizeBytes: 52428800 #50 * 1024 * 1024

druidcoordinator1:
  image: banno/druid-coordinator:latest
  links:
    - zookeeper
    - postgres
  ports:
    - "8081:8081"
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M
    druid_host: druidcoordinator1
    druid_port: 8081
    druid_zk_service_host: zookeeper:2181
    druid_metadata_storage_type: postgresql
    druid_metadata_storage_connector_connectURI: jdbc:postgresql://postgres:5432/druid
    druid_metadata_storage_connector_user: druid
    druid_metadata_storage_connector_password: diurd
    druid_coordinator_load_timeout: PT30S
    druid_coordinator_startDelay: PT5S

druidcoordinator2:
  image: banno/druid-coordinator:latest
  links:
    - zookeeper
    - postgres
  ports:
    - "8181:8181"
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M
    druid_host: druidcoordinator2
    druid_port: 8181
    druid_zk_service_host: zookeeper:2181
    druid_metadata_storage_type: postgresql
    druid_metadata_storage_connector_connectURI: jdbc:postgresql://postgres:5432/druid
    druid_metadata_storage_connector_user: druid
    druid_metadata_storage_connector_password: diurd
    druid_coordinator_load_timeout: PT30S
    druid_coordinator_startDelay: PT5S

druidhistorical1:
  image: banno/druid-historical:latest
  links:
    - zookeeper
    - hadoop
  ports:
    - "8083:8083"
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M -XX:MaxDirectMemorySize=6G
    druid_host: druidhistorical1
    druid_port: 8083
    druid_zk_service_host: zookeeper:2181
    druid_segmentCache_locations: "[{\"path\":\"/var/tmp/druid/indexCache\",\"maxSize\":5000000000}]"
    druid_processing_buffer_sizeBytes: 52428800 #50 * 1024 * 1024
    druid_server_maxSize: 5000000000
    druid_storage_type: hdfs
    druid_storage_storageDirectory: hdfs://hadoop:9000/druid

druidhistorical2:
  image: banno/druid-historical:latest
  links:
    - zookeeper
    - hadoop
  ports:
    - "8183:8183"
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M -XX:MaxDirectMemorySize=6G
    druid_host: druidhistorical2
    druid_port: 8183
    druid_zk_service_host: zookeeper:2181
    druid_segmentCache_locations: "[{\"path\":\"/var/tmp/druid/indexCache\",\"maxSize\":5000000000}]"
    druid_processing_buffer_sizeBytes: 52428800 #50 * 1024 * 1024
    druid_server_maxSize: 5000000000
    druid_storage_type: hdfs
    druid_storage_storageDirectory: hdfs://hadoop:9000/druid

druidoverlord1:
  image: banno/druid-overlord:latest
  links:
    - zookeeper
    - postgres
    - hadoop
  ports:
    - "8085:8085"
    - "8100:8100"
    - "8101:8101"
    - "8102:8102"
    - "8103:8103"
    - "8104:8104"
    - "8105:8105"
    - "8106:8106"
    - "8107:8107"
    - "8108:8108"
    - "8109:8109"
  volumes:
    - /Users:/Users #for local firehose in batch index tasks
  environment:
    DRUID_JAVA_OPTIONS: -Xmx512M
    druid_host: druidoverlord1
    druid_port: 8085
    druid_zk_service_host: zookeeper:2181
    druid_metadata_storage_type: postgresql
    druid_metadata_storage_connector_connectURI: jdbc:postgresql://postgres:5432/druid
    druid_metadata_storage_connector_user: druid
    druid_metadata_storage_connector_password: diurd
    druid_indexer_runner_type: local
    druid_indexer_storage_type: metadata
    druid_indexer_queue_startDelay: PT0M
    druid_indexer_runner_javaOpts: -server -Xmx256m
    druid_indexer_runner_startPort: 8100
    druid_indexer_fork_property_druid_processing_numThreads: 1
    druid_indexer_fork_property_druid_computation_buffer_size: 100000000
    druid_service: overlord
    druid_processing_buffer_sizeBytes: 26214400 #25 * 1024 * 1024
    druid_storage_type: hdfs
    druid_storage_storageDirectory: hdfs://hadoop:9000/druid
    druid_indexer_fork_property_druid_storage_type: hdfs
    druid_indexer_fork_property_druid_storage_storageDirectory: hdfs://hadoop:9000/druid
    druid_indexer_task_hadoopWorkingPath: hdfs://hadoop:9000/druid-working
    druid_indexer_task_defaultHadoopCoordinates: "[\"org.apache.hadoop:hadoop-client:2.3.0\"]"
